### ISSUE TITLE
[Button] Update styling

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#116]

**Comment by daniel-martic-sociomantic** [comment]
Icon size and spacing in button needs to be changed to correspond to design:

- icon size should be 24x24 (maybe just add padding since we don't want to make icon bigger, but rather the icon container)
-margins should be 8 between icon and button (currently 16 from button padding, so maybe add -8 to the icon) and 4 between icon and text

**Comment by damian-rodriguez-sociomantic** [comment]
design updates, reopening
