### ISSUE TITLE
[ All components ] role proptype conflicting with aria roles, linting error

### ISSUE THREAD

**Issue by eric-martinez-sociomantic** [sociomantic-tsunami/nessie#13]
~Rename proptype role of components to not conflict with aria roles:
https://www.w3.org/WAI/intro/aria~

~Affecting several components.~

- [x] ~Button~
- [x] ~ButtonRadio~
- [x] ~Column~
- [x] ~all H~
- [x] ~ModalDialog~
- [x] ~NavItem~
- [x] ~NavDropdown~
- [x] ~Paginator~
- [x] ~Proto/InputContainer~
- [x] ~Row~
- [x] ~Tooltip~
- [x] ~Tab~
- [x] ~TabButton~
- [x] ~Table~
- [x] ~TableCell~
- [x] ~TableRow~
- [x] ~Text~

**Comment by conor-cafferkey-sociomantic** [comment]
Just for some context: the reason we chose `role` (as opposed to, say, `presentation`) was to try to capture the semantic role / context in which the component is being used.

Possible alternatives to `role`:
- `variant` - a solid option, although the meaning is a little more vague that `role`
- `kind` - shorter to type than `variant`
- ~`context`~ - a bit closer to describing the intent of the prop, but ultimately a bit confusing...
- ..?

I guess, in the end, what we name the prop isn’t _too_ important tho. 

What’s more important is that the values that the prop accepts are semantic rather than presentational, e.g. a `primary` button not a `blueWithPolkaDots` button. And the presentation of that `role`/`variant`/`kind`/whatever is determined by the CSS theme.

**Comment by conor-cafferkey-sociomantic** [comment]
Revisiting this after some time I'm not so sure this is an issue at all: There are plenty of instances where prop names coincide with HTML attribute names and it's usually not confusing.

Since `variant` doesn't really capture the intention of this prop the same way that `role` does I think we should leave things as they are.

Let's just disabled the offending linter rule instead!
