### ISSUE TITLE
[Slider] feature request: add onMouseDown, onMouseUp

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/nessie#233]
as per issue https://github.com/sociomantic/ursula/issues/475 our ursula slider presenter requires to   "stage" the current value on dragging the slider knob and "commit" the value on click and on mouse up. The concept of staging and committing yields from UX requirements, e.g.  the presentation of other ui elements could be influenced by the staging value, or alerts wouldn't be shown prior to a commit etc.. 

### current

only handler prop is onChange which always fires when the underlying range input changes in any way 

### wanted

distinctive handler props `onDrag` (mousedown followed by mousemove event),`onMouseup` and `onClick`

**Comment by conor-cafferkey-sociomantic** [comment]
Thanks for the issue @kevin-krug-sociomantic! As discussed offline we’ll make the following callback props available:

- [ ] `onMouseDown`
- [ ] `onMouseUp`
- [ ] `onClick`

For each of the above it _might_ make sense to have separate events for the slider track and the slider handle(s), e.g: `onClickTrack`/`onClickHandle`.

The `onChange` prop already fires on dragging so this can be used to stage the value instead of an `onDrag` prop.

Besides the above props I noticed that we’re also missing the following 😱:
- [ ] `onMouseOver`
- [ ] `onMouseOut`
- [ ] `onBlur`
- [ ] `onFocus`

We’ll add those too as part of this issue!

**Comment by kevin-krug-sociomantic** [comment]
@conor-cafferkey-sociomantic great! As for our use case as `onChange` would be used to stage the value, that leaves just `onMouseUp` and `onClick` for our requirements in order to commit the staged value.

**Comment by conor-cafferkey-sociomantic** [comment]
Also seeing as the Slider value can be incremented/decremented using the up/down or left/right keys I guess we should also provide `onKeyPress` (and you should commit your staged value on this event).

**Comment by kevin-krug-sociomantic** [comment]
that's not that pressing as far as I see, as so far I don't see any UX requirement for interaction with up/down, currently in our app it's not supported
