### ISSUE TITLE
Test driver update for Tooltip and NavItem

### ISSUE THREAD

**Issue by damian-rodriguez-sociomantic** [sociomantic-tsunami/nessie#302]

**Comment by kevin-krug-sociomantic** [comment]
due to failing tests on Ursula's side we need to revert some changes made in release `5.11`(or decide on new driver methods), since now the wrappers of the tooltip and navitem changed (both changed to being the parent wrapping div). This led to tooltip's getContent driver method returning the parent div vs. the wrapped content and navitem driver method's executing on the parent div vs. the link as we except in our tests.
