### ISSUE TITLE
Safari thinks the fields are not complete without adding icons to them

### ISSUE THREAD

**Issue by tero-saarinen-sociomantic** [sociomantic-tsunami/nessie#4]
## Wanted

Hide safari autofill icons.

**Comment by conor-cafferkey-sociomantic** [comment]
Just for reference, the key icon below is what we’re talking about here:

<img width="99" alt="screen shot 2017-10-06 at 10 31 04" src="https://user-images.githubusercontent.com/13482427/31277786-e3cd8902-aaa2-11e7-9eaf-7014bd143705.png">

Safari doesn’t make it easy to disable this. In fact, turns out _all_ browsers ignore `autocomplete="off"` for password inputs 😒 

There is no doubt some hack that we can use to get rid of the icon. However, in general it’s not a good idea to override browser default behavior unless strictly necessary.

I’ll close this for now. We can reopen if we find that we absolutely must get rid of the icon.
